"""Pipeline provider abstraction (see ``app/providers/base.py``)."""

from app.providers.base import (
    NOT_CONFIGURED,
    SIMULATION,
    ComplianceRequest,
    ComplianceResult,
    ContentRequest,
    ContentResult,
    CreativeDirectionDraft,
    OpportunityDraft,
    PipelineProvider,
    ProductionRequest,
    ProductionResult,
    ProviderExecutionError,
    ProviderNotConfiguredError,
    ProviderUsage,
    RenderedAssetDraft,
    ResearchRequest,
    ResearchResult,
    ScriptDraft,
    SourceDraft,
    StrategyBriefDraft,
    StrategyRequest,
    StrategyResult,
)
from app.providers.null import NullPipelineProvider
from app.providers.registry import (
    PROVIDER_MODE_NULL,
    PROVIDER_MODE_SIMULATION,
    SUPPORTED_PROVIDER_MODES,
    get_pipeline_provider,
    provider_status,
)
from app.providers.simulation import SimulationPipelineProvider

__all__ = [
    "NOT_CONFIGURED",
    "PROVIDER_MODE_NULL",
    "PROVIDER_MODE_SIMULATION",
    "SIMULATION",
    "SUPPORTED_PROVIDER_MODES",
    "ComplianceRequest",
    "ComplianceResult",
    "ContentRequest",
    "ContentResult",
    "CreativeDirectionDraft",
    "NullPipelineProvider",
    "OpportunityDraft",
    "PipelineProvider",
    "ProductionRequest",
    "ProductionResult",
    "ProviderExecutionError",
    "ProviderNotConfiguredError",
    "ProviderUsage",
    "RenderedAssetDraft",
    "ResearchRequest",
    "ResearchResult",
    "ScriptDraft",
    "SimulationPipelineProvider",
    "SourceDraft",
    "StrategyBriefDraft",
    "StrategyRequest",
    "StrategyResult",
    "get_pipeline_provider",
    "provider_status",
]
