#!/usr/bin/env bash
# Cloud Agent install: durable, idempotent setup baked into the environment
# snapshot. Runs after the repository is checked out. Provisions PostgreSQL 16
# locally (Docker is not available in the Cloud Agent VM), Python deps for the
# API + worker, and web deps. Per-boot service startup lives in start.sh.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

PG_MAJOR=16
DEV_DB=content_orchestrator
TEST_DB=content_orchestrator_test

echo "==> [1/6] System packages (PostgreSQL ${PG_MAJOR}, python venv)"
if ! dpkg -s "postgresql-${PG_MAJOR}" >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    "postgresql-${PG_MAJOR}" "postgresql-client-${PG_MAJOR}" python3-venv
fi

echo "==> [2/6] Start local PostgreSQL cluster"
sudo pg_ctlcluster "${PG_MAJOR}" main start 2>/dev/null || true
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done
sudo -u postgres pg_isready

echo "==> [3/6] Ensure postgres password + application databases"
# TCP password auth for the migration/owner role used by DATABASE_URL.
sudo -u postgres psql -v ON_ERROR_STOP=1 -c "ALTER ROLE postgres WITH PASSWORD 'postgres';"
for db in "${DEV_DB}" "${TEST_DB}"; do
  if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${db}'" | grep -q 1; then
    sudo -u postgres createdb "${db}"
  fi
done
# The non-owner app_runtime role (RLS-scoped runtime traffic) is created by the
# first Alembic migration; nothing to do here.

echo "==> [4/6] Local .env (secrets generated once; never overwritten)"
if [ ! -f .env ]; then
  JWT="$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')"
  cat > .env <<EOF
# Generated by .cursor/cloud/install.sh for the Cloud Agent dev environment.
# Never commit this file (see .gitignore). Regenerate by deleting it and rerunning install.
ENVIRONMENT=development
LOG_LEVEL=INFO

DATABASE_URL=postgresql://postgres:postgres@localhost:5432/${DEV_DB}
APP_DATABASE_URL=postgresql://app_runtime:app_runtime@localhost:5432/${DEV_DB}

AUTH_MODE=local
SUPABASE_JWT_SECRET=${JWT}
SUPABASE_JWT_ALGORITHM=HS256
SUPABASE_JWT_AUDIENCE=authenticated

CORS_ALLOW_ORIGINS='["http://localhost:5173","http://127.0.0.1:5173"]'

DEFAULT_DAILY_SPEND_CAP_USD=50.0
DEFAULT_MONTHLY_SPEND_CAP_USD=1000.0

HEALTH_CHECK_INTERVAL_SECONDS=300
API_BASE_URL=http://127.0.0.1:8000
EOF
fi

echo "==> [5/6] Python venv + API/worker dependencies"
python3 -m venv .venv
# shellcheck disable=SC1091
. .venv/bin/activate
pip install --upgrade pip -q
pip install -e "apps/api[dev]" -e "apps/worker[dev]"

echo "==> [5b/6] Web dependencies"
( cd apps/web && npm ci )

echo "==> [6/6] Apply database migrations (dev + test)"
set -a
# shellcheck disable=SC1091
. ./.env
set +a
( cd apps/api && alembic upgrade head )
( cd apps/api \
  && DATABASE_URL="postgresql://postgres:postgres@localhost:5432/${TEST_DB}" \
     APP_DATABASE_URL="postgresql://app_runtime:app_runtime@localhost:5432/${TEST_DB}" \
     alembic upgrade head )

echo "==> install complete"
